blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://stackoverflow.com/questions/tagged/objectbox
    about: Ask how to do something with ObjectBox, or why something "isn't working" (Stack Overflow).
